# Generated by Django 3.0.6 on 2020-05-15 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=200, unique=True)),
                ('desc', models.TextField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('is_trashed', models.BooleanField()),
            ],
        ),
    ]
