# Generated by Django 3.0.6 on 2020-05-17 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0017_auto_20200516_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_trashed',
            field=models.BooleanField(default=False),
        ),
    ]
